apiVersion: v1
entries:
  id-vault:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-14T10:04:32.7901733Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 7d47676d69f942efebcdadc6def3457e7d53d1890bc944eecb8efe508c613366
    home: www.id-vault.com
    icon: www.id-vault.com
    name: id-vault
    urls:
    - id-vault-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-14T10:04:32.7807065Z"
